[package]
name = "ive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
ive_macros = { version = "0.1.0", path = "../ive_macros" }
